schema_version = "1.0.0"

id = "btb_wii_model_importer"
version = "0.1.0"
name = "Bob the Builder Wii Model Importer"
tagline = "Import H3M models from the Wii release of Bob the Builder: Festival of Fun"
maintainer = "jmancoder"
type = "add-on"
tags = ["Import-Export", "Mesh"]
blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
